[package]
authors = ["deciduously <github@deciduously.com>"]
name = "mifkad"
version = "0.1.1"
[[bin]]
name = "mifkad"
path = "src/backend/main.rs"

[dependencies]
actix = "0.7"
actix-web = "0.7"
calamine = "0.14"
chrono = "0.4"
error-chain = "0.12"
lazy_static = "1"
log = "0.4"
pretty_env_logger = "0.2"
regex = "1"
serde = "1"
serde_derive = "1"
serde_json = "1"

[dev-dependencies]
pretty_assertions = "0.5"