[package]
name = "mifkad"
version = "0.1.0"
authors = ["deciduously <github@deciduously.com>"]

[dependencies]

actix = "0.5"
actix-web = "0.6"
calamine = "0.14"
error-chain = "0.12"
log = "0.4"
pretty_env_logger = "0.2"

[dev-dependencies]

pretty_assertions = "0.5"